name: notify-teams

on:
  push:
    branches:
      - main

jobs:
    message_teams:
      runs-on: ubuntu-latest
      name: send message to teams
      steps:
        - uses: neonidian/teams-notify-build-status@v3
          with:
            # can be muli-line using YAML mult-line string
            webhookUrl: |
              ${{ secrets.TEAMSWEBHOOK }}
            ## title: Coming up next # Specify a title header
            ## titleBackgroundColor: green # allowed values are 'success', 'green', 'failure', 'red', 'cancelled', 'yellow', 'skipped', 'blue'
            ## status: test # appears in status label
            message: >-
              Next up is this and that
          env:
            SHOULD_DISPLAY_ACTOR_LABEL: false
            SHOULD_DISPLAY_VIEW_RUN_BUTTON: false
            SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: false