name: notify-teams

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    message_teams:
      runs-on: ubuntu-latest
      name: send message to teams
      steps:
        - uses: actions/checkout@v2
          with:
            token: ${{ secrets.JB_ACCESS_TOKEN }}
            submodules: true
        - run: |
            ./events-messenger/pwsh/Get-NextEvent.ps1 -path events-messenger/data/talks.csv
          shell: pwsh
          id: get-events
        - run: |
            ./events-messenger/pwsh/Send-TeamsMessage.ps1 -uri ${{secrets.TEAMSWEBHOOK}} -title "Coming up next" -message ${{steps.get-events.outputs.message}}
          shell: pwsh
          id: send-events
